# Generated by Django 3.0.3 on 2020-02-05 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('prog', 'Programming'), ('math', 'Mathematics'), ('fic', 'Fiction'), ('com', 'Comic Book'), ('myth', 'Mythology')], max_length=20)),
                ('pages', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=80)),
                ('last_name', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=254)),
                ('book_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles_api.Book')),
            ],
        ),
    ]
