# Generated by Django 3.0.3 on 2020-02-05 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0002_author_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='initials',
            field=models.CharField(default='', max_length=5),
            preserve_default=False,
        ),
    ]
