# Generated by Django 3.0.3 on 2020-02-05 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0003_author_initials'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='initials',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
