# Generated by Django 3.0.3 on 2020-02-05 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0005_book_sub_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='book_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='profiles_api.Book'),
        ),
    ]
